[phases.setup]
nixPkgs = ["nodejs_20"]

[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm ci --include=dev --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
