import fs from "node:fs";
const file = "FireboxAIStudio.jsx";
const lines = fs.readFileSync(file, "utf8").split("\n");
const start = lines.findIndex((line) => line.includes('                    <div style={{ flex:1, minHeight:0, overflowY:"auto", padding:"16px 18px"'));
const end = lines.findIndex((line, index) => index > start && line.includes('                    <div style={{ flexShrink:0, padding:"10px 10px 12px"'));
if (start < 0 || end < 0) throw new Error(`Activity panel bounds not found: ${start}, ${end}`);
const replacement = `                    <div style={{ flex:1, minHeight:0, overflowY:"auto", padding:"16px 18px", background:palette.editorBg }}>
                      <div style={{ color:palette.textMuted, fontSize:10, fontWeight:800, letterSpacing:"0.12em", marginBottom:10 }}>AGENT ACTIVITY</div>
                      <div style={{ display:"flex", alignItems:"center", justifyContent:"space-between", gap:10, padding:"14px", marginBottom:18, border:\`1px solid \${palette.border}\`, borderRadius:10, background:palette.panelBg }}>
                        <div style={{ display:"flex", alignItems:"center", gap:10, minWidth:0 }}><FireboxAgentMark size={21} animated={phase === "building" || aiThinking} state={phase === "error" ? "error" : phase === "complete" ? "complete" : "working"}/><div style={{ minWidth:0 }}><div style={{ color:palette.textFaint, fontSize:10, marginBottom:4 }}>Active task</div><div style={{ color:palette.textActive, fontSize:13, fontWeight:650, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>{description || currentProjectName || "Working on project"}</div></div></div><div style={{ display:"flex", alignItems:"center", gap:7, color:phase === "error" ? palette.error : phase === "complete" ? palette.success : palette.accent, fontSize:10, whiteSpace:"nowrap" }}>{phase === "building" && <Loader2 size={12} style={{ animation:"spin 1s linear infinite" }}/>} {phase === "building" ? "Working" : phase === "complete" ? "Complete" : phase === "error" ? "Failed" : "Ready"}<button title="Task menu" style={{ border:"none", background:"transparent", color:palette.textMuted, cursor:"pointer", fontSize:16, lineHeight:1 }}>⋯</button></div>
                      </div>
                      {liveActivity.length === 0 ? <div style={{ color:palette.textFaint, fontSize:12, lineHeight:1.7, padding:"4px 0 18px" }}>The Agent’s activity will appear here as Firebox works.</div> : <div style={{ display:"flex", flexDirection:"column", gap:16 }}>
                        {liveActivity.slice(-24).map(item => { const iconColor = item.status === "error" ? palette.error : item.status === "done" ? palette.success : palette.accent; const ActivityIcon = item.kind === "tool" ? Terminal : item.kind === "files" ? FileCode : item.kind === "preview" ? Eye : item.kind === "build" ? CheckCircle2 : item.kind === "repair" ? RotateCcw : item.status === "error" ? AlertTriangle : Sparkles; const expanded = expandedActivityId === item.id; const stamp = item.time ? new Date(item.time).toLocaleTimeString([], { hour:"2-digit", minute:"2-digit", second:"2-digit" }) : "now"; return <div key={item.id} onClick={() => item.status === "error" && setExpandedActivityId(expanded ? null : item.id)} style={{ display:"flex", alignItems:"flex-start", gap:10, fontSize:12, lineHeight:1.55, cursor:item.status === "error" ? "pointer" : "default" }}><ActivityIcon size={17} color={iconColor} strokeWidth={1.8} style={{ flexShrink:0, marginTop:2 }}/><div style={{ minWidth:0, flex:1 }}><div style={{ display:"flex", alignItems:"center", gap:7 }}><span style={{ color:palette.text, fontWeight:600 }}>{item.label}</span>{item.status === "working" && <Loader2 size={12} color={palette.accent} style={{ animation:"spin 1s linear infinite" }}/>} {item.status === "done" && <CheckCircle2 size={12} color={palette.success}/>} {item.status === "error" && <AlertTriangle size={12} color={palette.error}/>}<span style={{ marginLeft:"auto", color:palette.textFaint, fontSize:9 }}>{stamp}</span></div><div style={{ color:item.status === "error" ? palette.error : palette.textMuted, overflowWrap:"anywhere" }}>{item.text}</div>{item.details && expanded && <div style={{ marginTop:6, padding:"8px 9px", borderLeft:\`2px solid \${palette.error}\`, background:\`\${palette.error}10\`, color:palette.error, fontSize:10, whiteSpace:"pre-wrap", overflowWrap:"anywhere" }}>{item.details}</div>}</div></div>; })}
                        {(() => { const groups = liveActivity.reduce((map, item) => { const key = item.kind || "agent"; if (!map[key]) map[key] = []; map[key].push(item); return map; }, {}); return <div style={{ display:"flex", alignItems:"center", gap:6, flexWrap:"wrap", paddingTop:2 }}>{Object.entries(groups).map(([kind, items]) => { const Icon = kind === "tool" ? Terminal : kind === "files" ? FileCode : kind === "preview" ? Eye : kind === "build" ? CheckCircle2 : Sparkles; return <span key={kind} title={kind} style={{ display:"inline-flex", alignItems:"center", gap:5, color:palette.textMuted, fontSize:10 }}><span style={{ width:25, height:25, display:"inline-flex", alignItems:"center", justifyContent:"center", borderRadius:6, background:palette.panelBg, color:palette.accent }}><Icon size={13}/></span>{items.length}</span>; })}</div>; })()}
                      </div>}
                      <div style={{ display:"flex", alignItems:"center", gap:9, marginTop:18, paddingTop:14, borderTop:\`1px solid \${palette.border}\`, color:palette.textMuted, fontSize:11 }}><Clock3 size={15}/><span>{liveActivity.length} action{liveActivity.length === 1 ? "" : "s"}</span><span>Worked for {activityStartedAt ? Math.max(0, Math.floor((activityClock - new Date(activityStartedAt).getTime()) / 1000)) : 0} seconds</span></div>
                      {liveActivity.length > 0 && <div style={{ display:"flex", alignItems:"center", gap:9, marginTop:14, color:palette.success, fontSize:11 }}><CheckCircle2 size={15}/><span>{phase === "complete" ? "Checkpoint created just now" : "Checkpoint in progress"}</span></div>}
                      {workflowStage?.activity && <div style={{ marginTop:14, color:palette.textFaint, fontSize:11, lineHeight:1.5 }}>{workflowStage.activity}</div>}
                    </div>`;
lines.splice(start, end - start, replacement);
fs.writeFileSync(file, lines.join("\n"));
console.log(`Replaced activity panel lines ${start + 1}-${end}`);
