import fs from "node:fs";
const file = "FireboxAIStudio.jsx";
const lines = fs.readFileSync(file, "utf8").split("\n");
const start = lines.findIndex((line) => line.includes('                    <div style={{ flex:1, minHeight:0, overflowY:"auto", padding:"16px 18px"'));
const end = lines.findIndex((line, index) => index > start && line.includes('                    <div style={{ flexShrink:0, padding:"10px 10px 12px"'));
if (start < 0 || end < 0) throw new Error(`Activity bounds not found: ${start}, ${end}`);
const replacement = `                    <div style={{ flex:1, minHeight:0, overflowY:"auto", padding:"10px 0 8px", background:palette.editorBg }}>
                      {liveActivity.length === 0 ? <div style={{ padding:"18px 12px", color:palette.textFaint, fontSize:11, lineHeight:1.5 }}>Agent activity will appear here as Firebox works.</div> : <div style={{ display:"flex", flexDirection:"column" }}>
                        {liveActivity.slice(-40).map(item => { const iconColor = item.status === "error" ? palette.error : item.status === "done" ? palette.success : palette.accent; const ActivityIcon = item.kind === "tool" ? Terminal : item.kind === "files" ? FileCode : item.kind === "preview" ? Eye : item.kind === "build" ? CheckCircle2 : item.kind === "repair" ? RotateCcw : item.status === "error" ? AlertTriangle : Sparkles; const expanded = expandedActivityId === item.id; const stamp = item.time ? new Date(item.time).toLocaleTimeString([], { hour:"2-digit", minute:"2-digit", second:"2-digit" }) : ""; return <div key={item.id} onClick={() => item.status === "error" && setExpandedActivityId(expanded ? null : item.id)} style={{ display:"flex", alignItems:"flex-start", gap:9, minHeight:48, padding:"7px 12px", borderBottom:\`1px solid \${palette.border}55\`, cursor:item.status === "error" ? "pointer" : "default" }}><div style={{ width:20, flex:"0 0 20px", display:"flex", justifyContent:"center", paddingTop:3, color:iconColor }}><ActivityIcon size={15} strokeWidth={1.8}/></div><div style={{ minWidth:0, flex:1 }}><div style={{ display:"flex", alignItems:"center", gap:6, minWidth:0 }}><span style={{ color:palette.textActive, fontSize:11, fontWeight:650, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>{item.label}</span>{item.status === "working" && <Loader2 size={12} color={palette.accent} style={{ flexShrink:0, animation:"spin 1s linear infinite" }}/>} {item.status === "done" && <CheckCircle2 size={12} color={palette.success} style={{ flexShrink:0 }}/>} {item.status === "error" && <AlertTriangle size={12} color={palette.error} style={{ flexShrink:0 }}/>}<span style={{ marginLeft:"auto", flexShrink:0, color:palette.textFaint, fontSize:9, fontVariantNumeric:"tabular-nums" }}>{stamp}</span></div><div style={{ color:item.status === "error" ? palette.error : palette.textMuted, fontSize:10, lineHeight:1.45, overflowWrap:"anywhere" }}>{item.text}</div>{item.details && expanded && <div style={{ marginTop:5, padding:"6px 8px", borderLeft:\`2px solid \${palette.error}\`, background:\`\${palette.error}10\`, color:palette.error, fontSize:10, lineHeight:1.4, whiteSpace:"pre-wrap", overflowWrap:"anywhere" }}>{item.details}</div>}</div></div>; })}
                      </div>}
                    </div>`;
lines.splice(start, end - start, replacement);
fs.writeFileSync(file, lines.join("\n"));
console.log(`Applied screenshot activity layout at lines ${start + 1}-${end}`);
